FROM node:22-bookworm

ENV BODY_SIZE_LIMIT=11M

RUN sed -i 's|http://deb.debian.org|https://deb.debian.org|g' /etc/apt/sources.list.d/debian.sources && \
    apt-get update && \
    apt-get install -y --no-install-recommends ffmpeg curl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

# Install all deps (including dev)
RUN npm ci

COPY . .

RUN chmod +x /app/docker/entrypoint.sh \
  /app/docker/configure-prowlarr.sh

EXPOSE 3300 6881

ENTRYPOINT ["/app/docker/entrypoint.sh"]
