FROM node:22-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates curl ffmpeg && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

# Install all deps (including dev)
RUN npm ci

COPY . .

RUN chmod +x /app/docker/entrypoint.sh \
  /app/docker/configure-prowlarr.sh

EXPOSE 3300 6881

ENTRYPOINT ["/app/docker/entrypoint.sh"]
