import type { BrowseItem, DemoMember, DemoProfile, DemoSeasonSummary, DemoSettings, DemoUser } from '$lib/types';

const LOCAL_ARTWORK_BASE = '/media';

function getArtworkExtension(path: string | null) {
	if (!path) {
		return '.jpg';
	}

	const match = path.match(/\.[a-z0-9]+$/i);
	return match?.[0] ?? '.jpg';
}

function localArtworkUrl(kind: 'posters' | 'backdrops', id: string, sourcePath: string | null) {
	return sourcePath ? `${LOCAL_ARTWORK_BASE}/${kind}/${id}${getArtworkExtension(sourcePath)}` : null;
}

function makeSeasons(
	title: string,
	entryId: string,
	episodeCounts: number[],
	startYear: number,
	posterPath: string | null,
	overview: string
): DemoSeasonSummary[] {
	const seasonPoster = localArtworkUrl('posters', entryId, posterPath) ?? undefined;
	return episodeCounts.map((episodeCount, index) => ({
		seasonNumber: index + 1,
		name: `Season ${index + 1}`,
		episodeCount,
		year: startYear + index,
		posterPath: seasonPoster,
		overview: `${title} Season ${index + 1}. ${overview}`.slice(0, 180),
		airDate: `${startYear + index}-01-01`,
	}));
}

type CatalogEntry = BrowseItem;

type CatalogInput = {
	title: string;
	tmdbId: number;
	imdbId: string | null;
	year: number | null;
	posterPath: string | null;
	backdropPath: string | null;
	overview: string;
	voteAverage: number;
	genres: string[];
	certification: string | null;
	runtime: number | null;
	originalLanguage: string;
};

type ShowInput = CatalogInput & {
	totalSeasons: number;
	episodeCounts: number[];
};

function movieEntry(input: CatalogInput): CatalogEntry {
	const id = `movie-${input.tmdbId}`;
	return {
		id,
		tmdbId: input.tmdbId,
		imdbId: input.imdbId,
		title: input.title,
		year: input.year,
		posterUrl: localArtworkUrl('posters', id, input.posterPath),
		backdropUrl: localArtworkUrl('backdrops', id, input.backdropPath),
		overview: input.overview,
		voteAverage: input.voteAverage,
		genres: input.genres,
		mediaType: 'movie',
		certification: input.certification,
		needsResolve: false,
		runtime: input.runtime,
		originalLanguage: input.originalLanguage,
		totalSeasons: null,
	};
}

function showEntry(input: ShowInput): CatalogEntry {
	const id = `show-${input.tmdbId}`;
	return {
		id,
		tmdbId: input.tmdbId,
		imdbId: input.imdbId,
		title: input.title,
		year: input.year,
		posterUrl: localArtworkUrl('posters', id, input.posterPath),
		backdropUrl: localArtworkUrl('backdrops', id, input.backdropPath),
		overview: input.overview,
		voteAverage: input.voteAverage,
		genres: input.genres,
		mediaType: 'show',
		certification: input.certification,
		needsResolve: false,
		runtime: input.runtime,
		originalLanguage: input.originalLanguage,
		totalSeasons: input.totalSeasons,
		availableSeasons: makeSeasons(
			input.title,
			id,
			input.episodeCounts,
			input.year ?? new Date().getFullYear(),
			input.posterPath,
			input.overview
		),
	};
}

export const DEMO_USER: DemoUser = {
	id: 'user-demo',
	name: 'Dread Pirate Roberts',
	email: 'dpr@plank.com',
	image: null,
	role: 'admin',
};

export const DEMO_PROFILES: DemoProfile[] = [
	{
		id: 'profile-captain',
		name: 'Jolly Roger',
		logo: null,
		color: '#3b82f6',
		isMember: true,
		memberCount: 3,
		createdAt: '2026-04-27T00:00:00.000Z',
	},
	{
		id: 'profile-first-mate',
		name: 'Thousand Sunny',
		logo: null,
		color: '#ef4444',
		isMember: true,
		memberCount: 3,
		createdAt: '2026-04-27T00:00:00.000Z',
	},
	{
		id: 'profile-lookout',
		name: 'Black Pearl',
		logo: null,
		color: '#10b981',
		isMember: true,
		memberCount: 3,
		createdAt: '2026-04-27T00:00:00.000Z',
	},
];

export const DEMO_MEMBERS: Record<string, DemoMember[]> = {
	'profile-captain': [
		{
			id: 'member-owner',
			name: 'Captain James Hook',
			email: 'hook@plank.com',
			role: 'owner',
			image: null,
		},
		{
			id: 'member-smee',
			name: 'Mr. Smee',
			email: 'smee@plank.com',
			role: 'admin',
			image: null,
		},
		{
			id: 'member-starkey',
			name: 'Starkey',
			email: 'starkey@plank.com',
			role: 'member',
			image: null,
		},
	],
	'profile-first-mate': [
		{
			id: 'member-owner',
			name: 'Monkey D. Luffy',
			email: 'luffy@plank.com',
			role: 'owner',
			image: null,
		},
		{
			id: 'member-nami',
			name: 'Nami',
			email: 'nami@plank.com',
			role: 'admin',
			image: null,
		},
		{
			id: 'member-hongo',
			name: 'Hongo',
			email: 'hongo@plank.com',
			role: 'member',
			image: null,
		},
	],
	'profile-lookout': [
		{
			id: 'member-owner',
			name: 'Captain Jack Sparrow',
			email: 'sparrow@plank.com',
			role: 'owner',
			image: null,
		},
		{
			id: 'member-barbossa',
			name: 'Hector Barbossa',
			email: 'barbossa@plank.com',
			role: 'admin',
			image: null,
		},
		{
			id: 'member-turner',
			name: 'Will Turner',
			email: 'will.turner@plank.com',
			role: 'member',
			image: null,
		},
	],
};

export const DEMO_SETTINGS: DemoSettings = {
	tmdbApiKey: 'eed4e018645d5b4••••••••••••9725',
	opensubtitlesApiKey: 'sub-••••••••••••plank',
	opensubtitlesUsername: 'plank',
	opensubtitlesPassword: '••••••••••••',
	prowlarrUrl: 'https://search.plank.local',
	prowlarrApiKey: 'prwl-••••••••••••plank',
	trustedGroups: ['YTS', 'YIFY', '.BONE.', 'x1337', 'TVTEAM'],
	minSeeders: 5,
	indexers: [
		{ id: 'indexer-yts', name: 'YTS', kind: 'Movies', status: 'connected' },
		{ id: 'indexer-eztv', name: 'EZTV', kind: 'TV', status: 'connected' },
		{ id: 'indexer-1337x', name: '1337x', kind: 'General', status: 'limited' },
	],
};

export const CATALOG: CatalogEntry[] = [
	movieEntry({
		title: 'The Dark Knight',
		tmdbId: 155,
		imdbId: 'tt0468569',
		year: 2008,
		posterPath: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
		backdropPath: '/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg',
		overview:
			'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague Gotham as the Joker unleashes chaos.',
		voteAverage: 8.528,
		genres: ['Action', 'Crime', 'Thriller'],
		certification: 'PG-13',
		runtime: 152,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Inception',
		tmdbId: 27_205,
		imdbId: 'tt1375666',
		year: 2010,
		posterPath: '/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg',
		backdropPath: '/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
		overview:
			'Cobb, a skilled thief who steals secrets by infiltrating the subconscious, is offered a chance to regain his old life in exchange for performing the impossible task of inception.',
		voteAverage: 8.372,
		genres: ['Action', 'Science Fiction', 'Adventure'],
		certification: 'PG-13',
		runtime: 148,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Mad Max: Fury Road',
		tmdbId: 76_341,
		imdbId: 'tt1392190',
		year: 2015,
		posterPath: '/hA2ple9q4qnwxp3hKVNhroipsir.jpg',
		backdropPath: '/uT895WNwm0aIJRtGizcQhrejWUo.jpg',
		overview:
			'In a post-apocalyptic wasteland, Max teams up with the fierce Imperator Furiosa to flee a tyrant and his army in a high-speed battle for survival.',
		voteAverage: 7.6,
		genres: ['Action', 'Adventure', 'Science Fiction'],
		certification: 'R',
		runtime: 121,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'The Matrix',
		tmdbId: 603,
		imdbId: 'tt0133093',
		year: 1999,
		posterPath: '/aOIuZAjPaRIE6CMzbazvcHuHXDc.jpg',
		backdropPath: '/tlm8UkiQsitc8rSuIAscQDCnP8d.jpg',
		overview:
			'A computer hacker learns that reality is a simulated world controlled by machines and joins an underground rebellion to fight back.',
		voteAverage: 8.243,
		genres: ['Action', 'Science Fiction'],
		certification: 'R',
		runtime: 136,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Dune',
		tmdbId: 438_631,
		imdbId: 'tt1160419',
		year: 2021,
		posterPath: '/gDzOcq0pfeCeqMBwKIJlSmQpjkZ.jpg',
		backdropPath: '/qVgZu5BTx6pu4owCvVOm4zjTfOi.jpg',
		overview:
			'Paul Atreides travels to the most dangerous planet in the universe to ensure the future of his family and his people.',
		voteAverage: 7.8,
		genres: ['Science Fiction', 'Adventure'],
		certification: 'PG-13',
		runtime: 155,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'The Shawshank Redemption',
		tmdbId: 278,
		imdbId: 'tt0111161',
		year: 1994,
		posterPath: '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
		backdropPath: '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
		overview:
			'Andy Dufresne, sentenced to life at Shawshank, forms a quiet friendship with Red and holds onto hope through decades behind bars.',
		voteAverage: 8.719,
		genres: ['Drama', 'Crime'],
		certification: 'R',
		runtime: 142,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Pulp Fiction',
		tmdbId: 680,
		imdbId: 'tt0110912',
		year: 1994,
		posterPath: '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
		backdropPath: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
		overview:
			'Hit men, a boxer, a mob boss, and a pair of bandits collide in a darkly comic crime story that loops through time.',
		voteAverage: 8.5,
		genres: ['Thriller', 'Crime', 'Comedy'],
		certification: 'R',
		runtime: 154,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Parasite',
		tmdbId: 496_243,
		imdbId: 'tt6751668',
		year: 2019,
		posterPath: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
		backdropPath: '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
		overview:
			'A poor family ingratiates itself with a wealthy household until a shocking turn turns class ambition into disaster.',
		voteAverage: 8.494,
		genres: ['Comedy', 'Thriller', 'Drama'],
		certification: 'R',
		runtime: 133,
		originalLanguage: 'ko',
	}),
	movieEntry({
		title: 'No Country for Old Men',
		tmdbId: 6977,
		imdbId: 'tt0477348',
		year: 2007,
		posterPath: '/6d5XOczc226jECq0LIX0siKtgHR.jpg',
		backdropPath: '/gddUsvfyySrM5k8B8wwJy2VRlBx.jpg',
		overview:
			'After stumbling onto a drug deal gone wrong, Llewelyn Moss becomes the target of a relentless killer while an aging sheriff tries to make sense of the violence.',
		voteAverage: 7.951,
		genres: ['Crime', 'Thriller', 'Western'],
		certification: 'R',
		runtime: 122,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Whiplash',
		tmdbId: 244_786,
		imdbId: 'tt2582802',
		year: 2014,
		posterPath: '/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
		backdropPath: '/wbQa0EnWUyRzQ5d1pHLNRlmsCUP.jpg',
		overview:
			'An ambitious young drummer pushes himself to the brink under the brutal training of a merciless music instructor.',
		voteAverage: 8.375,
		genres: ['Drama', 'Music', 'Thriller'],
		certification: 'R',
		runtime: 107,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'The Grand Budapest Hotel',
		tmdbId: 120_467,
		imdbId: 'tt2278388',
		year: 2014,
		posterPath: '/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
		backdropPath: '/9udCLTxTFl28RxnK8Q05E154ZGa.jpg',
		overview:
			'A legendary concierge and his young protege become entangled in a stolen painting, a family fortune, and a changing Europe.',
		voteAverage: 8.03,
		genres: ['Comedy', 'Drama'],
		certification: 'R',
		runtime: 100,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Superbad',
		tmdbId: 8363,
		imdbId: 'tt0829482',
		year: 2007,
		posterPath: '/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg',
		backdropPath: '/giYuvpmpZbwkT3NtX4WdNYqGhxw.jpg',
		overview:
			'Two inseparable high school seniors try to survive one chaotic night before graduation tears them apart.',
		voteAverage: 7.261,
		genres: ['Comedy'],
		certification: 'R',
		runtime: 113,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Everything Everywhere All at Once',
		tmdbId: 545_611,
		imdbId: 'tt6710474',
		year: 2022,
		posterPath: '/u68AjlvlutfEIcpmbYpKcdi09ut.jpg',
		backdropPath: '/6zV1AJUj0EzsJV05Ru2lfAWIn3R.jpg',
		overview:
			'An exhausted woman is pulled into a multiverse-spanning adventure and discovers only she can save everything that matters to her.',
		voteAverage: 7.719,
		genres: ['Action', 'Adventure', 'Science Fiction'],
		certification: 'R',
		runtime: 140,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Knives Out',
		tmdbId: 546_554,
		imdbId: 'tt8946378',
		year: 2019,
		posterPath: '/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
		backdropPath: '/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg',
		overview:
			'Detective Benoit Blanc investigates the death of a famous novelist and untangles a maze of lies inside an eccentric family.',
		voteAverage: 7.839,
		genres: ['Comedy', 'Crime', 'Mystery'],
		certification: 'PG-13',
		runtime: 131,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Get Out',
		tmdbId: 419_430,
		imdbId: 'tt5052448',
		year: 2017,
		posterPath: '/mE24wUCfjK8AoBBjaMjho7Rczr7.jpg',
		backdropPath: '/o8dPH0ZSIyyViP6rjRX1djwCUwI.jpg',
		overview: `A weekend visit with his girlfriend's family turns into a nightmare when Chris uncovers the horrifying truth behind their hospitality.`,
		voteAverage: 7.622,
		genres: ['Mystery', 'Thriller', 'Horror'],
		certification: 'R',
		runtime: 104,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'A Quiet Place',
		tmdbId: 447_332,
		imdbId: 'tt6644200',
		year: 2018,
		posterPath: '/nAU74GmpUk7t5iklEp3bufwDq4n.jpg',
		backdropPath: '/nHRUtBwFNnNN70vcQ7lAsjc2T6S.jpg',
		overview:
			'A family lives in silence while hiding from creatures that hunt by sound in a world where a single noise can kill.',
		voteAverage: 7.4,
		genres: ['Horror', 'Drama', 'Science Fiction'],
		certification: 'PG-13',
		runtime: 91,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Hereditary',
		tmdbId: 493_922,
		imdbId: 'tt7784604',
		year: 2018,
		posterPath: '/hjlZSXM86wJrfCv5VKfR5DI2VeU.jpg',
		backdropPath: '/gJbTXKNTL6O7r7PzF6ZRkJGBlPp.jpg',
		overview:
			'After a family matriarch dies, her daughter and grandchildren unravel a terrifying inheritance and descend toward madness.',
		voteAverage: 7.293,
		genres: ['Horror', 'Mystery', 'Thriller'],
		certification: 'R',
		runtime: 128,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'The Shining',
		tmdbId: 694,
		imdbId: 'tt0081505',
		year: 1980,
		posterPath: '/uAR0AWqhQL1hQa69UDEbb2rE5Wx.jpg',
		backdropPath: '/mmd1HnuvAzFc4iuVJcnBrhDNEKr.jpg',
		overview:
			'A winter caretaker at the Overlook Hotel slowly loses his grip on sanity while his son senses the evil trapped inside.',
		voteAverage: 8.205,
		genres: ['Horror', 'Thriller'],
		certification: 'R',
		runtime: 144,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Spider-Man: Into the Spider-Verse',
		tmdbId: 324_857,
		imdbId: 'tt4633694',
		year: 2018,
		posterPath: '/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
		backdropPath: '/8mnXR9rey5uQ08rZAvzojKWbDQS.jpg',
		overview:
			'Miles Morales becomes Spider-Man and joins heroes from across the multiverse to stop Kingpin from tearing reality apart.',
		voteAverage: 8.393,
		genres: ['Animation', 'Action', 'Adventure', 'Science Fiction'],
		certification: 'PG',
		runtime: 117,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Coco',
		tmdbId: 354_912,
		imdbId: 'tt2380307',
		year: 2017,
		posterPath: '/6Ryitt95xrO8KXuqRGm1fUuNwqF.jpg',
		backdropPath: '/g7CHF8gTLGooTbP4GznIGwaqAGL.jpg',
		overview:
			'Miguel journeys into the Land of the Dead to uncover the true story of his family and his love of music.',
		voteAverage: 8.197,
		genres: ['Family', 'Animation', 'Music', 'Adventure'],
		certification: 'PG',
		runtime: 105,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'The Lion King',
		tmdbId: 8587,
		imdbId: 'tt0110357',
		year: 1994,
		posterPath: '/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg',
		backdropPath: '/6GF9uJs7AnbcJvyfoZyjZv063Oo.jpg',
		overview: 'Young Simba must confront loss, betrayal, and destiny to reclaim his place in the Circle of Life.',
		voteAverage: 8.253,
		genres: ['Animation', 'Family', 'Drama'],
		certification: 'G',
		runtime: 89,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Spirited Away',
		tmdbId: 129,
		imdbId: 'tt0245429',
		year: 2001,
		posterPath: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
		backdropPath: '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
		overview:
			'Chihiro becomes trapped in a spirit world and must find the courage to save her parents and return home.',
		voteAverage: 8.533,
		genres: ['Animation', 'Family', 'Fantasy'],
		certification: 'PG',
		runtime: 125,
		originalLanguage: 'ja',
	}),
	showEntry({
		title: 'Breaking Bad',
		tmdbId: 1396,
		imdbId: null,
		year: 2008,
		posterPath: '/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
		backdropPath: '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
		overview: `Walter White, a New Mexico chemistry teacher, turns to making meth to secure his family's future after a terminal cancer diagnosis.`,
		voteAverage: 8.943,
		genres: ['Drama', 'Crime'],
		certification: 'TV-MA',
		runtime: 47,
		originalLanguage: 'en',
		totalSeasons: 5,
		episodeCounts: [7, 13, 13, 13, 16],
	}),
	showEntry({
		title: 'Stranger Things',
		tmdbId: 66_732,
		imdbId: null,
		year: 2016,
		posterPath: '/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg',
		backdropPath: '/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
		overview:
			'A boy vanishes in Hawkins, Indiana, and his friends uncover secret experiments, supernatural terror, and a mysterious girl with powers.',
		voteAverage: 8.6,
		genres: ['Sci-Fi & Fantasy', 'Mystery', 'Action & Adventure'],
		certification: 'TV-14',
		runtime: 50,
		originalLanguage: 'en',
		totalSeasons: 5,
		episodeCounts: [8, 9, 8, 9, 8],
	}),
	showEntry({
		title: 'The Office (US)',
		tmdbId: 2316,
		imdbId: null,
		year: 2005,
		posterPath: '/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg',
		backdropPath: '/mLyW3UTgi2lsMdtueYODcfAB9Ku.jpg',
		overview: `The employees of Dunder Mifflin's Scranton branch navigate mundane office life with awkward humor, petty rivalries, and surprising warmth.`,
		voteAverage: 8.6,
		genres: ['Comedy'],
		certification: 'TV-14',
		runtime: 22,
		originalLanguage: 'en',
		totalSeasons: 9,
		episodeCounts: [6, 22, 25, 19, 28, 26, 26, 24, 25],
	}),
	showEntry({
		title: 'Succession',
		tmdbId: 76_331,
		imdbId: null,
		year: 2018,
		posterPath: '/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg',
		backdropPath: '/bcdUYUFk8GdpZJPiSAas9UeocLH.jpg',
		overview:
			'The Roy family battles for control of a media empire as their aging patriarch begins to step back from power.',
		voteAverage: 8.278,
		genres: ['Drama', 'Comedy'],
		certification: 'TV-MA',
		runtime: 60,
		originalLanguage: 'en',
		totalSeasons: 4,
		episodeCounts: [10, 10, 9, 10],
	}),
	showEntry({
		title: 'Severance',
		tmdbId: 95_396,
		imdbId: null,
		year: 2022,
		posterPath: '/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg',
		backdropPath: '/ixgFmf1X59PUZam2qbAfskx2gQr.jpg',
		overview:
			'Mark leads a team of employees whose memories have been surgically split between work and personal life, until a mystery exposes the truth behind their jobs.',
		voteAverage: 8.398,
		genres: ['Drama', 'Mystery', 'Sci-Fi & Fantasy'],
		certification: 'TV-MA',
		runtime: 50,
		originalLanguage: 'en',
		totalSeasons: 3,
		episodeCounts: [9, 10, 10],
	}),
	showEntry({
		title: 'Arcane',
		tmdbId: 94_605,
		imdbId: null,
		year: 2021,
		posterPath: '/abf8tHznhSvl9BAElD2cQeRr7do.jpg',
		backdropPath: '/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg',
		overview: `Sisters Vi and Jinx are pulled to opposite sides of a conflict between Piltover's progress and Zaun's unrest.`,
		voteAverage: 8.755,
		genres: ['Animation', 'Action & Adventure', 'Sci-Fi & Fantasy'],
		certification: 'TV-14',
		runtime: 42,
		originalLanguage: 'en',
		totalSeasons: 2,
		episodeCounts: [9, 9],
	}),
	showEntry({
		title: 'The Bear',
		tmdbId: 136_315,
		imdbId: null,
		year: 2022,
		posterPath: '/eKfVzzEazSIjJMrw9ADa2x8ksLz.jpg',
		backdropPath: '/wHNwlE6ftEpgjVbdhLXOtv1hLs0.jpg',
		overview: `Carmy returns to Chicago to run his family's sandwich shop and discovers that rebuilding the kitchen means rebuilding himself too.`,
		voteAverage: 8.2,
		genres: ['Drama', 'Comedy'],
		certification: 'TV-MA',
		runtime: 31,
		originalLanguage: 'en',
		totalSeasons: 4,
		episodeCounts: [8, 10, 10, 10],
	}),
	showEntry({
		title: 'Fallout',
		tmdbId: 106_379,
		imdbId: null,
		year: 2024,
		posterPath: '/c15BtJxCXMrISLVmysdsnZUPQft.jpg',
		backdropPath: '/cIgHBLTMbcIkS0yvIrUUVVKLdOz.jpg',
		overview:
			'Two centuries after the apocalypse, the residents of luxury vaults are forced into a violent wasteland full of factions, monsters, and buried secrets.',
		voteAverage: 8.122,
		genres: ['Action & Adventure', 'Sci-Fi & Fantasy'],
		certification: 'TV-MA',
		runtime: 56,
		originalLanguage: 'en',
		totalSeasons: 2,
		episodeCounts: [8, 8],
	}),
	showEntry({
		title: 'Squid Game',
		tmdbId: 93_405,
		imdbId: null,
		year: 2021,
		posterPath: '/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg',
		backdropPath: '/2meX1nMdScFOoV4370rqHWKmXhY.jpg',
		overview: `Desperate contestants accept an invitation to compete in deadly versions of children's games for a life-changing prize.`,
		voteAverage: 7.855,
		genres: ['Action & Adventure', 'Mystery', 'Drama'],
		certification: 'TV-MA',
		runtime: 55,
		originalLanguage: 'ko',
		totalSeasons: 3,
		episodeCounts: [9, 7, 6],
	}),
	movieEntry({
		title: 'Glass Onion',
		tmdbId: 661_374,
		imdbId: 'tt11564570',
		year: 2022,
		posterPath: '/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg',
		backdropPath: '/dKqa850uvbNSCaQCV4Im1XlzEtQ.jpg',
		overview:
			'Benoit Blanc heads to Greece to peel back the layers of a mystery surrounding a tech billionaire and his circle of friends.',
		voteAverage: 7,
		genres: ['Comedy', 'Crime', 'Mystery'],
		certification: 'PG-13',
		runtime: 140,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'The Irishman',
		tmdbId: 398_978,
		imdbId: 'tt1302006',
		year: 2019,
		posterPath: '/mbm8k3GFhXS0ROd9AD1gqYbIFbM.jpg',
		backdropPath: '/1RDto0tLo8Fhq7OcwgDaM7nECb7.jpg',
		overview:
			'Frank Sheeran recalls his long career as a hitman and the alliances that tied organized crime to labor politics.',
		voteAverage: 7.575,
		genres: ['Crime', 'Drama', 'History'],
		certification: 'R',
		runtime: 209,
		originalLanguage: 'en',
	}),
	showEntry({
		title: 'Andor',
		tmdbId: 83_867,
		imdbId: null,
		year: 2022,
		posterPath: '/khZqmwHQicTYoS7Flreb9EddFZC.jpg',
		backdropPath: '/ajztm40qDPqMONaSJhQ2PaNe2Xd.jpg',
		overview:
			'Cassian Andor is pulled into a growing rebellion and discovers how much he can change the fight against the Empire.',
		voteAverage: 8.287,
		genres: ['Sci-Fi & Fantasy', 'Action & Adventure', 'Drama'],
		certification: 'TV-14',
		runtime: 42,
		originalLanguage: 'en',
		totalSeasons: 2,
		episodeCounts: [12, 12],
	}),
	movieEntry({
		title: 'Turning Red',
		tmdbId: 508_947,
		imdbId: 'tt8097030',
		year: 2022,
		posterPath: '/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg',
		backdropPath: '/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg',
		overview:
			'Thirteen-year-old Mei discovers that excitement transforms her into a giant red panda, complicating family, school, and friendship.',
		voteAverage: 7.317,
		genres: ['Animation', 'Family', 'Comedy', 'Fantasy'],
		certification: 'PG',
		runtime: 100,
		originalLanguage: 'en',
	}),
	showEntry({
		title: 'Yellowstone',
		tmdbId: 73_586,
		imdbId: null,
		year: 2018,
		posterPath: '/peNC0eyc3TQJa6x4TdKcBPNP4t0.jpg',
		backdropPath: '/ynSOcgDLZfdLCZfRSYZGiTgYJVo.jpg',
		overview:
			'The Dutton family defends the largest ranch in the United States against rival developers, reservation politics, and their own internal fractures.',
		voteAverage: 8.253,
		genres: ['Western', 'Drama'],
		certification: 'TV-MA',
		runtime: 47,
		originalLanguage: 'en',
		totalSeasons: 5,
		episodeCounts: [9, 10, 10, 8, 14],
	}),
	movieEntry({
		title: 'Palm Springs',
		tmdbId: 587_792,
		imdbId: 'tt9484998',
		year: 2020,
		posterPath: '/gnAfqiV7yO3Jq9IntTmwkcaICqc.jpg',
		backdropPath: '/d7JUXVvjvVCXWs1mlpyO5ESdWdT.jpg',
		overview:
			'Two wedding guests get trapped in a time loop and are forced to confront themselves while falling for each other.',
		voteAverage: 7.337,
		genres: ['Comedy', 'Romance', 'Science Fiction'],
		certification: 'R',
		runtime: 90,
		originalLanguage: 'en',
	}),
	showEntry({
		title: 'The Last of Us',
		tmdbId: 100_088,
		imdbId: null,
		year: 2023,
		posterPath: '/dmo6TYuuJgaYinXBPjrgG9mB5od.jpg',
		backdropPath: '/lY2DhbA7Hy44fAKddr06UrXWWaQ.jpg',
		overview:
			'Joel is tasked with smuggling Ellie across a ruined America, and their journey becomes a brutal fight for survival and connection.',
		voteAverage: 8.434,
		genres: ['Drama'],
		certification: 'TV-MA',
		runtime: 55,
		originalLanguage: 'en',
		totalSeasons: 2,
		episodeCounts: [9, 7],
	}),
	movieEntry({
		title: 'Dune: Part Two',
		tmdbId: 693_134,
		imdbId: 'tt15239678',
		year: 2024,
		posterPath: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
		backdropPath: '/eZ239CUp1d6OryZEBPnO2n87gMG.jpg',
		overview:
			'Paul Atreides unites with Chani and the Fremen while seeking revenge against the forces that destroyed his family.',
		voteAverage: 8.126,
		genres: ['Science Fiction', 'Adventure'],
		certification: 'PG-13',
		runtime: 167,
		originalLanguage: 'en',
	}),
	showEntry({
		title: 'The Boys',
		tmdbId: 76_479,
		imdbId: null,
		year: 2019,
		posterPath: '/in1R2dDc421JxsoRWaIIAqVI2KE.jpg',
		backdropPath: '/bq28ajZaoMyzEIm6REelqyqtEDZ.jpg',
		overview:
			'A group of vigilantes takes on corrupt superheroes using blue-collar grit and a willingness to fight dirty.',
		voteAverage: 8.437,
		genres: ['Sci-Fi & Fantasy', 'Action & Adventure'],
		certification: 'TV-MA',
		runtime: 58,
		originalLanguage: 'en',
		totalSeasons: 5,
		episodeCounts: [8, 8, 8, 8, 8],
	}),
	movieEntry({
		title: 'Top Gun: Maverick',
		tmdbId: 361_743,
		imdbId: 'tt1745960',
		year: 2022,
		posterPath: '/n0YuM4f5lvGAP6MAW2kBIzugXnc.jpg',
		backdropPath: '/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg',
		overview:
			'After more than thirty years of service, Pete “Maverick” Mitchell returns to train a new class of TOP GUN pilots for a mission unlike any before.',
		voteAverage: 8.152,
		genres: ['Action', 'Drama'],
		certification: 'PG-13',
		runtime: 131,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'John Wick',
		tmdbId: 245_891,
		imdbId: 'tt2911666',
		year: 2014,
		posterPath: '/wXqWR7dHncNRbxoEGybEy7QTe9h.jpg',
		backdropPath: '/ff2ti5DkA9UYLzyqhQfI2kZqEuh.jpg',
		overview:
			'Ex-hitman John Wick comes out of retirement to hunt down the gangsters who took everything from him.',
		voteAverage: 7.454,
		genres: ['Action', 'Thriller'],
		certification: 'R',
		runtime: 101,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Blade Runner 2049',
		tmdbId: 335_984,
		imdbId: 'tt1856101',
		year: 2017,
		posterPath: '/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
		backdropPath: '/askFH4GSk2u9z3ZE5ypdKIMeqLJ.jpg',
		overview:
			'Officer K uncovers a buried secret that sends him on a search for Rick Deckard, a blade runner missing for thirty years.',
		voteAverage: 7.592,
		genres: ['Science Fiction', 'Drama'],
		certification: 'R',
		runtime: 164,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Tenet',
		tmdbId: 577_922,
		imdbId: 'tt6723592',
		year: 2020,
		posterPath: '/aCIFMriQh8rvhxpN1IWGgvH0Tlg.jpg',
		backdropPath: '/7BYtnXUfweV6EryNYDpZFeS31Ia.jpg',
		overview:
			'Armed with only one word, a secret operative navigates international espionage and time inversion to prevent global catastrophe.',
		voteAverage: 7.174,
		genres: ['Action', 'Thriller', 'Science Fiction'],
		certification: 'PG-13',
		runtime: 150,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Goodfellas',
		tmdbId: 769,
		imdbId: 'tt0099685',
		year: 1990,
		posterPath: '/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg',
		backdropPath: '/gILte6Zd7m1YneIr6MVhh30S9pr.jpg',
		overview:
			'Henry Hill is pulled deep into the mafia under the guidance of Jimmy Conway and learns what a life in organized crime really costs.',
		voteAverage: 8.5,
		genres: ['Drama', 'Crime'],
		certification: 'R',
		runtime: 145,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'The Godfather',
		tmdbId: 238,
		imdbId: 'tt0068646',
		year: 1972,
		posterPath: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
		backdropPath: '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
		overview:
			'The aging patriarch of the Corleone family transfers control of his crime empire to his reluctant son Michael.',
		voteAverage: 8.7,
		genres: ['Drama', 'Crime'],
		certification: 'R',
		runtime: 175,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Oppenheimer',
		tmdbId: 872_585,
		imdbId: 'tt15398776',
		year: 2023,
		posterPath: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
		backdropPath: '/neeNHeXjMF5fXoCJRsOmkNGC7q.jpg',
		overview:
			'The story of J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.',
		voteAverage: 8.032,
		genres: ['Drama', 'History'],
		certification: 'R',
		runtime: 181,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'There Will Be Blood',
		tmdbId: 7345,
		imdbId: 'tt0469494',
		year: 2007,
		posterPath: '/fa0RDkAlCec0STeMNAhPaF89q6U.jpg',
		backdropPath: '/9UAKA6ceZi6TgQwTAAMt7DWwYPI.jpg',
		overview:
			'Oil prospector Daniel Plainview builds an empire in California while a bitter rivalry with a preacher corrodes everyone around him.',
		voteAverage: 8.076,
		genres: ['Drama'],
		certification: 'R',
		runtime: 158,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Moonlight',
		tmdbId: 376_867,
		imdbId: 'tt4975722',
		year: 2016,
		posterPath: '/qLnfEmPrDjJfPyyddLJPkXmshkp.jpg',
		backdropPath: '/jm1oD3eB08LImSwL1LrzF9AJQ5b.jpg',
		overview:
			'A young man struggles to find himself across three defining chapters of his life while wrestling with love, identity, and belonging.',
		voteAverage: 7.357,
		genres: ['Drama'],
		certification: 'R',
		runtime: 111,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Hot Fuzz',
		tmdbId: 4638,
		imdbId: 'tt0425112',
		year: 2007,
		posterPath: '/zPib4ukTSdXvHP9pxGkFCe34f3y.jpg',
		backdropPath: '/9rMSCFH9zhv1vILpEZQlUJs9iUm.jpg',
		overview:
			'A top London cop is transferred to a sleepy village where a string of “accidents” suggests something much darker is going on.',
		voteAverage: 7.562,
		genres: ['Crime', 'Action', 'Comedy'],
		certification: 'R',
		runtime: 121,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'The Big Short',
		tmdbId: 318_846,
		imdbId: 'tt1596363',
		year: 2015,
		posterPath: '/scVEaJEwP8zUix8vgmMoJJ9Nq0w.jpg',
		backdropPath: '/l2Lqkfjq1k5pG2gZXD4qSiyrJ0.jpg',
		overview: 'A handful of outsiders see the 2008 financial crisis coming and decide to bet against the system.',
		voteAverage: 7.364,
		genres: ['Comedy', 'Drama'],
		certification: 'R',
		runtime: 131,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Booksmart',
		tmdbId: 505_600,
		imdbId: 'tt1489887',
		year: 2019,
		posterPath: '/2aSxRDmisJP90H3S0aocyuQIe4z.jpg',
		backdropPath: '/cheDSO3mYmsAFQlRM91o7MK6Wcc.jpg',
		overview:
			'Two academic overachievers try to cram four years of missed fun into one wild night before graduation.',
		voteAverage: 7.011,
		genres: ['Comedy'],
		certification: 'R',
		runtime: 102,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Midsommar',
		tmdbId: 530_385,
		imdbId: 'tt8772262',
		year: 2019,
		posterPath: '/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg',
		backdropPath: '/pYgj8e2Y6RufnSyOA6OnzmxFXxZ.jpg',
		overview:
			'A trip to a remote Swedish festival gradually transforms from a dream vacation into a sunlit nightmare.',
		voteAverage: 7.152,
		genres: ['Horror', 'Drama', 'Mystery'],
		certification: 'R',
		runtime: 147,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Scream',
		tmdbId: 4232,
		imdbId: 'tt0117571',
		year: 1996,
		posterPath: '/lr9ZIrmuwVmZhpZuTCW8D9g0ZJe.jpg',
		backdropPath: '/vh7np635kDIcfO6x2Y9ElgLJsuI.jpg',
		overview:
			'A masked killer stalks Sidney Prescott and her friends in a deadly game shaped by the rules of horror movies.',
		voteAverage: 7.429,
		genres: ['Crime', 'Horror', 'Mystery'],
		certification: 'R',
		runtime: 112,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Spider-Man: Across the Spider-Verse',
		tmdbId: 569_094,
		imdbId: 'tt9362722',
		year: 2023,
		posterPath: '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
		backdropPath: '/9xfDWXAUbFXQK585JvByT5pEAhe.jpg',
		overview:
			'Miles Morales is launched across the multiverse and forced to redefine what it means to be Spider-Man.',
		voteAverage: 8.332,
		genres: ['Animation', 'Action', 'Adventure', 'Science Fiction'],
		certification: 'PG',
		runtime: 140,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: `Guillermo del Toro's Pinocchio`,
		tmdbId: 555_604,
		imdbId: 'tt1488589',
		year: 2022,
		posterPath: '/vx1u0uwxdlhV2MUzj4VlcMB0N6m.jpg',
		backdropPath: '/qXOxYzPSPY9viZTgs7O6vNBOB7Y.jpg',
		overview:
			'A wooden boy brought magically to life struggles to live up to his father’s expectations in fascist Italy.',
		voteAverage: 8,
		genres: ['Animation', 'Fantasy', 'Adventure', 'Drama'],
		certification: 'PG',
		runtime: 117,
		originalLanguage: 'en',
	}),
	movieEntry({
		title: 'Akira',
		tmdbId: 149,
		imdbId: 'tt0094625',
		year: 1988,
		posterPath: '/neZ0ykEsPqxamsX6o5QNUFILQrz.jpg',
		backdropPath: '/fK40VGYIm7hmKrLJ26fgPQU0qRG.jpg',
		overview: 'A secret military project turns a biker into a psychic threat that could destroy Neo-Tokyo.',
		voteAverage: 7.943,
		genres: ['Animation', 'Science Fiction', 'Action'],
		certification: 'R',
		runtime: 124,
		originalLanguage: 'ja',
	}),
	showEntry({
		title: 'Shogun',
		tmdbId: 126_308,
		imdbId: null,
		year: 2024,
		posterPath: '/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg',
		backdropPath: '/6Tb87q9Tog30F5AAHh1gyDT2Vve.jpg',
		overview:
			'Lord Toranaga fights for survival in feudal Japan after an English pilot and a mysterious ship change the balance of power.',
		voteAverage: 8.422,
		genres: ['Drama', 'War & Politics'],
		certification: 'TV-MA',
		runtime: null,
		originalLanguage: 'en',
		totalSeasons: 1,
		episodeCounts: [10],
	}),
	showEntry({
		title: 'True Detective S1',
		tmdbId: 46_648,
		imdbId: null,
		year: 2014,
		posterPath: '/zYqVTiHK5ZajYcNzAW7qWte5NWS.jpg',
		backdropPath: '/v8YFr8BbU9qsO8PYIulzTeM6Qk.jpg',
		overview:
			'A haunted detective anthology where investigations uncover dark secrets in both the case and the people assigned to solve it.',
		voteAverage: 8.287,
		genres: ['Drama', 'Mystery'],
		certification: 'TV-MA',
		runtime: null,
		originalLanguage: 'en',
		totalSeasons: 4,
		episodeCounts: [8, 8, 8, 6],
	}),
	showEntry({
		title: 'Ted Lasso',
		tmdbId: 97_546,
		imdbId: null,
		year: 2020,
		posterPath: '/5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg',
		backdropPath: '/gEQkOMmnJcoh9Hh1vk7fpVYnksR.jpg',
		overview:
			'An American football coach takes over an English soccer club and wins over a skeptical team with optimism and stubborn kindness.',
		voteAverage: 8.34,
		genres: ['Drama', 'Comedy'],
		certification: 'TV-MA',
		runtime: null,
		originalLanguage: 'en',
		totalSeasons: 3,
		episodeCounts: [10, 12, 12],
	}),
	showEntry({
		title: 'Black Mirror',
		tmdbId: 42_009,
		imdbId: null,
		year: 2011,
		posterPath: '/seN6rRfN0I6n8iDXjlSMk1QjNcq.jpg',
		backdropPath: '/dg3OindVAGZBjlT3xYKqIAdukPL.jpg',
		overview:
			'An anthology of unsettling near-future stories exploring how technology amplifies humanity’s darkest instincts.',
		voteAverage: 8.283,
		genres: ['Sci-Fi & Fantasy', 'Drama', 'Mystery'],
		certification: 'TV-MA',
		runtime: null,
		originalLanguage: 'en',
		totalSeasons: 7,
		episodeCounts: [3, 4, 6, 6, 3, 5, 6],
	}),
	showEntry({
		title: 'House of the Dragon',
		tmdbId: 94_997,
		imdbId: null,
		year: 2022,
		posterPath: '/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg',
		backdropPath: '/2xGcSLyTAzConiHAByWqhfLiatT.jpg',
		overview:
			'The Targaryen dynasty sits at the height of its power as a brutal succession struggle begins to tear the realm apart.',
		voteAverage: 8.288,
		genres: ['Sci-Fi & Fantasy', 'Drama', 'Action & Adventure'],
		certification: 'TV-MA',
		runtime: null,
		originalLanguage: 'en',
		totalSeasons: 2,
		episodeCounts: [10, 8],
	}),
	showEntry({
		title: `X-Men '97`,
		tmdbId: 138_502,
		imdbId: null,
		year: 2024,
		posterPath: '/9Ycz7yYRf9V4jk3YXwcZhFtbNcF.jpg',
		backdropPath: '/iDnTAeR2WNA62XQG0ivtteDSjd5.jpg',
		overview:
			'The X-Men return to protect a world that fears them and confront a future more dangerous than they expected.',
		voteAverage: 8.499,
		genres: ['Animation', 'Action & Adventure', 'Sci-Fi & Fantasy'],
		certification: 'TV-PG',
		runtime: null,
		originalLanguage: 'en',
		totalSeasons: 1,
		episodeCounts: [10],
	}),
	showEntry({
		title: 'Mr. Robot',
		tmdbId: 62_560,
		imdbId: null,
		year: 2015,
		posterPath: '/kv1nRqgebSsREnd7vdC2pSGjpLo.jpg',
		backdropPath: '/hZOuVkhAWX9viLJuaIsMh8cM3Jz.jpg',
		overview:
			'A brilliant but isolated hacker is recruited into a movement aimed at taking down the corporations that shape the world.',
		voteAverage: 8.3,
		genres: ['Crime', 'Drama'],
		certification: 'TV-MA',
		runtime: null,
		originalLanguage: 'en',
		totalSeasons: 4,
		episodeCounts: [10, 12, 10, 13],
	}),
	showEntry({
		title: 'Fleabag',
		tmdbId: 67_070,
		imdbId: null,
		year: 2016,
		posterPath: '/27vEYsRKa3eAniwmoccOoluEXQ1.jpg',
		backdropPath: '/hXdQ4MWsEOX6qg6VydKrLb3YJ4g.jpg',
		overview:
			'A dry-witted woman tries to navigate grief, family, and modern life in London while exposing every contradiction to the audience.',
		voteAverage: 8.3,
		genres: ['Comedy', 'Drama'],
		certification: 'TV-MA',
		runtime: null,
		originalLanguage: 'en',
		totalSeasons: 2,
		episodeCounts: [6, 6],
	}),
];

export const CATALOG_BY_ID = Object.fromEntries(CATALOG.map((entry) => [entry.id, entry])) as Record<
	string,
	CatalogEntry
>;

export const TRENDING_IDS = [...CATALOG]
	.sort((a, b) => (b.year ?? 0) - (a.year ?? 0) || (b.voteAverage ?? 0) - (a.voteAverage ?? 0))
	.map((entry) => entry.id);

export const POPULAR_IDS = [...CATALOG]
	.sort((a, b) => (b.voteAverage ?? 0) - (a.voteAverage ?? 0) || (b.year ?? 0) - (a.year ?? 0))
	.map((entry) => entry.id);

export const SEEDED_LIBRARY_IDS: Record<string, string[]> = {
	'profile-captain': [
		'movie-155',
		'movie-603',
		'movie-438631',
		'movie-680',
		'movie-278',
		'movie-324857',
		'show-1396',
		'show-95396',
		'show-2316',
	],
	'profile-first-mate': [
		'movie-27205',
		'movie-76341',
		'movie-244786',
		'movie-546554',
		'movie-419430',
		'movie-545611',
		'show-94605',
		'show-136315',
	],
	'profile-lookout': [
		'movie-354912',
		'movie-129',
		'movie-447332',
		'movie-120467',
		'movie-8587',
		'movie-496243',
		'show-66732',
		'show-76331',
	],
};

export const SEEDED_SEASON_NUMBERS: Record<string, number[]> = {
	'show-1396': [1, 2],
	'show-95396': [1],
	'show-2316': [1],
	'show-94605': [1],
	'show-136315': [1],
	'show-66732': [1, 2],
	'show-76331': [1],
};

export const SEEDED_PROGRESS: Record<string, { playPosition: number; playDuration: number }> = {
	'movie-438631': { playPosition: 5580, playDuration: 9300 },
	'show-1396': { playPosition: 1260, playDuration: 2820 },
	'show-94605': { playPosition: 1410, playDuration: 2520 },
	'show-66732': { playPosition: 1740, playDuration: 3000 },
};
